# Generated by Django 4.2.3 on 2023-07-14 16:24

from django.db import migrations, models
import petstagram_try.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_tagged_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images', validators=[petstagram_try.photos.validators.validate_file_size]),
        ),
    ]
